#!/bin/sh
#PBS -l walltime=168:00:00
#PBS -N tvem_test42
#PBS -l nodes=1:ppn=1

# Load R
module load r/3.5.1

# change to directory where 'qsub' was called
cd funmediation

# run my program
Rscript ./CTRC_4004_250.R > test42.out