#!/bin/sh
#PBS -l walltime=168:00:00
#PBS -N tvem_test32
#PBS -l nodes=1:ppn=1

# Load R
module load r/3.5.1

# change to directory where 'qsub' was called
cd funmediation

# run my program
Rscript ./CTRC_3003_250.R > test32.out