#!/bin/sh
#PBS -l walltime=168:00:00
#PBS -N tvem_test21_2
#PBS -l nodes=1:ppn=1

# Load R
module load r/4.0.2

# change to directory where 'qsub' was called
cd funmediation

# run my program
Rscript ./CTRC_2002_1000_2.R > test21_2.out